### ISSUE TITLE
SSL certificate for Caleydo Website

### ISSUE THREAD

**Issue by thinkh** [Caleydo/caleydo.github.io#101]
The HTTPS version of the Caleydo Website produces a [certificate error](https://www.caleydo.org/). It would be good to fix that and always use the HTTPS version (since it's also rewarded by Google with a higher rank).

@ngehlenborg or @mstreit Do you know how it works with the domain administration and/or Nils' webspace/AWS?

**Comment by keckelt** [comment]
Cutom domains for github pages gained HTTPS support in May 2018: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Also see #160
