### ISSUE TITLE
Links to Domino web prototype broken/missing

### ISSUE THREAD

**Issue by carowjp** [Caleydo/caleydo.github.io#103]
The link given on the Domino page to the web prototype http://demo.caleydo.org/domino_js/ is broken.

The Domino app is missing from the list of applications on the Caleydo Web platform page http://demo.caleydo.org/

**Comment by thinkh** [comment]
We moved the Domino example to http://playground.caleydo.org/domino_js/.
Please keep in mind that this example is not complete and might be buggy.

**Comment by mstreit** [comment]
We need to update the link on the website: http://www.caleydo.org/tools/domino/
