### ISSUE TITLE
Fix row off-by-one error in Caleydo.d3.parser.parseMatrix

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#104]
(Retitled to reflect course of action. Also, I suppose this isn't really a bug in this project, so it's ok if this should be closed and we reopen on a different repo.)

original description:
>
Follow up to #99 and https://github.com/Caleydo/caleydo.github.io/commit/5ff29f3efa23b4ce244fbd095be15b04f52e808b#commitcomment-18910944 : If three arguments should be used, should we error is only one is supplied? Or is there a story where we do need the one argument form? Sorry to belabor this.

**Comment by mstreit** [comment]
I think the argument checking is fine. According to the code, both col ids and row ids are optional. If the col ids argument is missing, it takes the content of the first column and if the row id argument is missing, it takes the first row. However, the current implementation is buggy obviously.

**Comment by mstreit** [comment]
See overloaded parseMatrix function in
https://github.com/Caleydo/caleydo_d3/blob/master/parser.ts

**Comment by thinkh** [comment]
These two commits fixed your bug:
* https://github.com/Caleydo/caleydo_d3/commit/d3b1b64243076d4fb11382f77ab5e717991751b0#diff-119bd0b0cc6d4cc8b7bedf23956a06cf
* https://github.com/Caleydo/caleydo_d3/commit/4803f08927caf55d6e71e69cd112e13304b135b1#diff-119bd0b0cc6d4cc8b7bedf23956a06cf

**Comment by thinkh** [comment]
@mccalluc Just for your information: As far as I could see, the parseMatrix and parseRemoteMatrix isn't used in Caleydo. So you can modify it as you want.
