### ISSUE TITLE
403 from S3 for JS bundles

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#105]
All the iframes on http://www.caleydo.org/documentation/tutorial/web_bundle/ are empty because S3 is not serving the bundles:
```
$ curl -I https://s3.amazonaws.com/latest/caleydo.js
HTTP/1.1 403 Forbidden
```

S3 defaults to tight security: not a hard fix. Assigning to self to make sure I have privs to this bucket

**Comment by thinkh** [comment]
Ehm... Did you tried it also with [the links I provided](https://github.com/Caleydo/caleydo.github.io/issues/94#issuecomment-244869934)?
