### ISSUE TITLE
Travis tests of tutorial examples?

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#110]
If we have more tutorial examples, it will probably help to have tests to make sure they're working. Possibilities:

- qunit, or something like that, run by phantomjs. The examples would need to change, so that instead of just doing stuff, they defined functions, and we could make assertions about the behavior of those functions. Too much paperwork? and it also makes the examples less clear.
- Go all the way to selenium? Since I'm not so concerned about interaction at this point, that seems like overkill.
- Just use phantomjs directly, load frame.html?1, or something like that, and make sure the results are what we want? Seems best at this moment.

Not a rush.

**Comment by ngehlenborg** [comment]
I second that. There is nothing worse than broken demos. 

Also: interaction will become important very quickly. We might want to plan for that. Not sure if there is any literature out there on testing visualization tools.

**Comment by thinkh** [comment]
I also aggree that we should more go into testing, especially for Tutorials and Caleydo Web Apps that are deployed at http://demo.caleydo.org.

As Chuck mentioned we can start with testing the Caleydo core and data-driven part and then move to the UI.

This link gives some [good entry points](http://stackoverflow.com/questions/15801757/testing-d3-and-other-svg-based-web-applications).

**Comment by mccalluc** [comment]
Tests are pretty much caught up with the examples (almost: test_3 was failing for me). The idea is to create a test_n.js in parallel with each demo_n.js. For the most part, I am just testing that expected substrings occur in the HTML.

Tests are only being run with FF. Other browsers are possible, but it would be some work. See #116.
