### ISSUE TITLE
Minimal tutorial example of CLUE

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#111]
I've just pushed a branch, mccalluc/clue-tutorial, with only

```
Caleydo.clue.template.create(document.body, {})
```
- Internally, $ is undefined, though it's available at the top level. How to fix that?
- Is there additional CSS that a minimal CLUE application needs to include?
- Next steps?

**Comment by mstreit** [comment]
It does not make much sense to add the whole clue plugin as a dependency to the lib version, because it comes with all the Bootstrap GUI (header, mode switcher, provenance visualization, etc.). We will change it in a way that the provenance graph will be stored in the core. @thinkh will update the ticket if this is done.

**Comment by thinkh** [comment]
Removed dependencies with commit https://github.com/Caleydo/bundle_lib/commit/6b7a473be77179f6b43ee47329ce3f656af864a3

**Comment by thinkh** [comment]
According to issue https://github.com/Caleydo/caleydo_core/issues/2 we moved the provenance tracking into the core. That facilitates recording actions and storing them in the provenance graph and doesn't require caleydo_clue as dependency anymore. Only if you want to have the full "CLUE experience", i.e. the interface for annotations, story-editing and so on, you have to add caleydo_clue as dependency. For the library that would not be the use case.

**Comment by mstreit** [comment]
In the library only tutorial we could show how actions can be pushed into the provenance graph (when the user makes a selection, for instance). The provenance graph could be given as an input to the graph view that renders a graph using a force directed layout. This would be a very nice demonstration of the provenance tracking capabilities in our framework.

**Comment by mccalluc** [comment]
Reopening to resolve original problems. CLUE is part of web bundle; no additional js dependencies are necessary. I want to construct a simple, testable example of its usage, but want to fill in the earlier part of the tutorial first.

**Comment by mccalluc** [comment]
Closing in favor of https://github.com/phovea/phovea.github.io/issues/38
