### ISSUE TITLE
Test other browsers besides FF

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#116]
- Chrome?
- Opera?
- Safari?

I'm imagining a test matrix on Travis: Besides simply configuring Selenium, we'll need to download and install (and cache?) the other browsers.

**Comment by mstreit** [comment]
We should definitely run the tests on Chrome too, because this is the browser that we suggest to use for our demos (such as the ones on vistories.org). However, testing the other browsers might be useful too, if it's not too much extra work for us.

**Comment by mccalluc** [comment]
So it looks like some folks have gotten chrome to work on travis... but it might be tricky. If it feels like I'm getting stuck, I should shift gears and use Saucelabs:
- We have minimal tests on Refinery which are using it successfully
- They take care of all the browsers

On the other hand:
- It is another 3rd partly service to depend on and to manage credentials for
- Much of their offering (videos etc) is overkill if we're just running qunit

**Comment by mstreit** [comment]
I haven't worked with Saucelabs so far and therefore cannot provide any further input here. For now, we could just stick to FF testing I guess.

**Comment by mccalluc** [comment]
(Another possible direction is [Karma](https://karma-runner.github.io/1.0/plus/travis.html): I think what it does well is giving feedback about JS unit tests, particularly during development, but it doesn't make Chrome testing on Travis any easier, and you have less browser control than with Selenium. But it's out there.)

**Comment by mccalluc** [comment]
Putting this on the back burner: I think it's [possible](http://blog.500tech.com/setting-up-travis-ci-to-run-tests-on-latest-google-chrome-version/), though we'd also need to install [chromedriver](https://sites.google.com/a/chromium.org/chromedriver)... If we really needed this, better to hide the complexity with SauceLabs, than to maintain it ourselves.

(I'd feel different about this if it were the other way around, but with Chrome getting actual eyeballs, it feels pretty safe just to keep the FF test as a backstop.)

**Comment by mstreit** [comment]
I agree.

**Comment by mccalluc** [comment]
@mstreit : I'm going to close this:
- I think we're going in a direction where there will be testing on each repo. I have set up Saucelabs for caleydo_core in my branch, and we could configure different browsers there. Another reason for a code review and merge :)
- Conversely, I think it is very good to be able to run selenium tests without saucelabs, and firefox is easiest on Travis: Saucelabs is a good tool, but I don't want to depend on it exclusively.
