### ISSUE TITLE
finish documenting range methods

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#130]
For some, I didn't understand the behavior. For others, I wasn't sure if it was a method we really expected end users to use.
- [ ] isAll
- [ ] isNone
- [ ] first
- [ ] last
- [ ] ndim
- [ ] clone
- [ ] swap
- [ ] filter
- [ ] dim
- [ ] invert
- [ ] indexRangeOf
- [ ] indexOf
- [ ] size
- [ ] split
- [ ] product

**Comment by mstreit** [comment]
@sgratzl, can you please briefly go through the list and tick the items that are supposed to be exposed.

**Comment by mccalluc** [comment]
At this moment, I don't think the tutorial needs to be the place that explains everything: Generated documentation for methods would be better. https://github.com/Caleydo/caleydo.github.io/issues/164#issuecomment-263994099
