### ISSUE TITLE
"GET /api/idtype" ... Why?

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#132]
Web bundle v0.0.1 makes AJAX GETs to /api/idtype, which fail for me because I am not running the server. Is this ok?
- As a browser looking at the console, it seems like something might be broken.
- Is there some other way I could / should provide the information it's looking for?

**Comment by thinkh** [comment]
I haven't debugged it, but assume that the call is triggered in [idtype.fillUp()](https://github.com/Caleydo/caleydo_core/blob/master/idtype.ts#L1002) when using [idtype.list()](https://github.com/Caleydo/caleydo_core/blob/master/idtype.ts#L1031). 

A possible to prevent the call is to set the library into the [offline mode](https://github.com/Caleydo/caleydo_core/blob/master/main.ts#L33). However, I don't know the side effects in the Caleydo library.

**Comment by mccalluc** [comment]
replaced by https://github.com/phovea/phovea.github.io/issues/39
