### ISSUE TITLE
Heatmaps on Firefox blocky ... then blurry

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#140]
-    web_bundle version: v0.0.1
-    browser version: FF 42.01
-    OS: Mac
### Reproducer:

``` javascript
function demo_5($target) {
  var sequence = Array.from(Array(100).keys()).map(function(x){return x-50;});
  var matrix = Caleydo.d3.parser.parseMatrix(
      // times table
      sequence.map(function (m) {
        return sequence.map(function (n) {
          return m * n;
        })
      }),
      sequence, // row_ids
      sequence // col_ids
  );


  Caleydo.core.multiform.create(
      matrix.view(Caleydo.core.range.parse('(1:100:5),(0:40:2,60:100:2)')),
      $target[0],
      {initialVis: 'caleydo-vis-heatmap'}
  );

  Caleydo.core.multiform.create(
      matrix.view(Caleydo.core.range.parse('(1:100:5),(0:40,60:100)')),
      $target[0],
      {initialVis: 'caleydo-vis-heatmap'}
  );

}
```
### Observed behavior:

FF top / Chrome bottom
<img width="651" alt="screen shot 2016-09-16 at 9 35 35 am" src="https://cloud.githubusercontent.com/assets/730388/18587713/561d866a-7bf1-11e6-918a-6ec03a5c2215.png">
### Expected behavior:

If possible:
- Thin white lines should not appear between blocks with smaller datasets
- The map should not get blurry with large datasets.

**Comment by thinkh** [comment]
> Thin white lines should not appear between blocks with smaller datasets

I assume that is a rendering problem of the browser. We saw that behavior also in [TaCo](https://github.com/Caleydo/taco) when we rendered the diff heatmap using multiple tiny blocks (as div elements). I think you cannot prevent that unless, you use the heatmap canvas implementation.

> The map should not get blurry with large datasets.

That might be also a browser rendering issue. I'm not sure if we can fix this bug/behavior.

**Comment by mccalluc** [comment]
Look into https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering or https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled ... though fiddling right now it does not seem to have fixed anything.

**Comment by mccalluc** [comment]
Closing as 'won't-fix'. If it becomes a priority, open a new bug in a phovea repo.
