### ISSUE TITLE
Are the first and second dimensions of ranges reversed?

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#142]
- web_bundle version: v0.0.1
### Reproducer:

``` javascript
function demo_5($target) {
  var sequence = Array.from(Array(100).keys());
  var matrix = Caleydo.d3.parser.parseMatrix(
      // times table
      sequence.map(function (m) {
        return sequence.map(function (n) {
          return m * n;
        })
      }),
      sequence, // row_ids
      sequence // col_ids
  );

  Caleydo.core.multiform.create(
      matrix.view(Caleydo.core.range.parse('(1:100:10,1:100:10,1:100:10),(40:60)')),
      $target[0],
      {initialVis: 'caleydo-vis-heatmap'}
  );
}
```
### Observed behavior:

<img width="160" alt="screen shot 2016-09-16 at 10 05 10 am" src="https://cloud.githubusercontent.com/assets/730388/18588597/20f319ec-7bf5-11e6-970d-faa502a6b05e.png">

The heatmap repeats vertically.
### Expected behavior:

Naively, I would expect a repetition in the first dimension of the range to produce a repetition along the horizontal axis? (Tables display the same behavior: This is not a problem with heatmap.)

**Comment by mccalluc** [comment]
- check if this is just heatmaps
- check with sgraitzl about dependencies.

**Comment by mccalluc** [comment]
@sgratzl : I'm in the process of moving bugs to the correct repo, but I'm not sure whether this is a bug. Can you comment?

**Comment by sgratzl** [comment]
dim 0 = rows
dim 1 = cols
or what do you mean?

**Comment by mccalluc** [comment]
Yep, that's fine: I was thinking of (x,y) coordinates when I first looked at this, but I do think now that row/column is more common than the other way around. Thanks!

https://books.google.com/ngrams/graph?content=column+row%2Crow+column&year_start=1920&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Ccolumn%20row%3B%2Cc0%3B.t1%3B%2Crow%20column%3B%2Cc0

and confirmed by 

https://www.google.com/trends/explore?q=%22column%20row%22,%22row%20column%22
