### ISSUE TITLE
Allow HTTPS connections to caleydo.org

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo.github.io#160]
Getting a certificate from https://letsencrypt.org/ might be an option. But the certs are only valid for 60 days and need to be renewed regularly.

**Comment by sgratzl** [comment]
see also https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc and isaacs/github#156

**Comment by sgratzl** [comment]
see also https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc and isaacs/github#156

**Comment by keckelt** [comment]
As described in #110, custom domains for github pages got SSL support in May 2018 (see [blog post](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/)).

The configured A Name for the github page pointed to `192.30.252.153`, which seems autodated:

> `If you're using an A record that points to 192.30.252.153 or 192.30.252.154, you'll need to update your DNS settings for your site to be available over HTTPS`
Source: [Troubleshooting custom domains](https://help.github.com/articles/troubleshooting-custom-domains/)

After updating the A record, I had to remvoed and added the custom domain from the repo settings:

> After updating existing DNS settings, you may need to remove and re-add your custom domain to your GitHub account to trigger the process of enabling HTTPS.
Source: [Troubleshooting custom domains](https://help.github.com/articles/troubleshooting-custom-domains/)


And now it works :lock:

**Comment by thinkh** [comment]
Awesome, thanks @keckelt!

**Comment by keckelt** [comment]
I have added [SSL certificates for our forward domains](https://github.com/phovea/phovea_landing_page/pull/9).
So these should no longer give you security alerts:

- https://stratomex.caleydo.org
- https://lineup.caleydo.org
- https://ordino.caleydo.org

**Comment by mstreit** [comment]
Thanks!
