### ISSUE TITLE
Web Bundle Tutorial: Choose other default options for demo 3 + 4

### ISSUE THREAD

**Issue by thinkh** [Caleydo/caleydo.github.io#161]
- web_bundle version: 0.0.1
- browser version: Firefox 49.0.1
- OS: Windows 10
### Reproducer:

Open [Demo 3](http://www.caleydo.org/documentation/tutorial/web_bundle/frame.html?3) and [Demo 4](http://www.caleydo.org/documentation/tutorial/web_bundle/frame.html?4)
### Observed behavior:

![web_bundle_tutorial_demo3](https://cloud.githubusercontent.com/assets/5851088/18877472/a6c0da1a-84cd-11e6-987e-d0c2a30f8fb2.PNG)
### Expected behavior:

A different default selection from the two drop downs that give a better impression, e.g. as follows:

![web_bundle_tutorial_demo3_expected](https://cloud.githubusercontent.com/assets/5851088/18877513/c563e750-84cd-11e6-867b-50a95bcb3f5d.PNG)

**Comment by mccalluc** [comment]
@thinkh: Do you know how to do this? I tried for a bit but didn't figure it out.

**Comment by thinkh** [comment]
1. [Extend the options](https://github.com/Caleydo/caleydo_vis/blob/master/scatterplot.ts#L16)
2. [Replace the default selectedIndex](https://github.com/Caleydo/caleydo_vis/blob/master/scatterplot.ts#L45)

Alternatively (and maybe better), would be to pass the column name and you select the index by this name.

**Comment by mccalluc** [comment]
I think this is not a rare use case, and configuring it should be easier. I've filed https://github.com/phovea/phovea_vis/issues/5. Closing.
