### ISSUE TITLE
Web Bundle Tutorial: Selection highlight in scatterplot is not working

### ISSUE THREAD

**Issue by thinkh** [Caleydo/caleydo.github.io#162]
- web_bundle version: 0.0.1
- browser version: Firefox 49.0.1
- OS: Windows 10
### Reproducer:

Open [Demo 3](http://www.caleydo.org/documentation/tutorial/web_bundle/frame.html?3) and [Demo 4](http://www.caleydo.org/documentation/tutorial/web_bundle/frame.html?4)
### Observed behavior:

Selection highlight is missing in scatter plots and cannot select items in scatterplots.

![missing_selection_highlight](https://cloud.githubusercontent.com/assets/5851088/18877671/34294ff4-84ce-11e6-8138-16512713d8cb.PNG)
### Expected behavior:

Dots in scatterplot should be selectable and highlighted.
If a table row is selected the dot should be highlighted in the scatterplot.

**Comment by mccalluc** [comment]
@thinkh: Do you know whether I'm doing something wrong in the tutorial, or if this is just not implemented in phovea? If you could copy-and-paste this to either https://github.com/phovea/phovea.github.io or https://github.com/phovea/phovea_vis accordingly, I'd appreciate it. Thanks!

**Comment by mccalluc** [comment]
#146 suggests this is just not implemented.

**Comment by mccalluc** [comment]
Replaced by https://github.com/phovea/phovea_vis/issues/8
