### ISSUE TITLE
Data Structures Tutorial: Explain source code better

### ISSUE THREAD

**Issue by thinkh** [Caleydo/caleydo.github.io#163]
- web_bundle version: 0.0.1
- browser version: Firefox 49.0.1
- OS: Windows 10
### Reproducer:

Open [Data Structures Tutorial](http://www.caleydo.org/documentation/tutorial/data_structures/)
### Observed behavior:

The source code is not really self-explained and hard to understand if you have less programming knowledge and/or not familiar with Caleydo.

A few examples:

``` javascript
  var sequence = Array.from(Array(200).keys())
      .map(function(x){return (x-100)/50;});
```

or

``` javascript
      sequence.map(function (m) {
        return sequence.map(function (n) {
          // Gentle gradient across the whole thing...
          // with ripples in the middle.
          return m*n + Math.sin(1/(m*m+n*n));
        })
      }),
      sequence, // row_ids
      sequence // col_ids
```

What does `matrix.view(parse('(0:200:5),(0:200:5)')),` do?
### Expected behavior:

Please add more comments, either as commend in the source code (prefered) or as text in the Markdown file.

**Comment by mccalluc** [comment]
replaced.
