### ISSUE TITLE
Angular Tutorial: Selection highlight does not work

### ISSUE THREAD

**Issue by thinkh** [Caleydo/caleydo.github.io#165]
- web_bundle version: v0.0.1
- browser version: Firefox 49.0.1
- OS: Windows 10
### Reproducer:

Open [Demo 9](http://www.caleydo.org/documentation/tutorial/web_bundle/frame_angular_good.html?9) and click a heat map cell.
### Observed behavior:

The heat map cell is not highlighted.
### Expected behavior:

The heat map cell should be highlighted. The CSS class `caleydo-select-selected` is already set to the selected rect element.

**Comment by thinkh** [comment]
I assume that the caleydo.css is not imported in this example.

**Comment by mccalluc** [comment]
moved to phovea
