### ISSUE TITLE
Clean up playground list

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#174]
- [ ] http://playground.caleydo.org/caleydo_importer/ is blank with console error: “TypeError: this.root.createShadowRoot is not a function”
- [ ] caleydo_importer homepage and repo links are identical.
- [ ] particles lists as its homepage caleydo.org
- [ ] http://playground.caleydo.org/caleydo_vis_proteinviewer/ is blank: It has a 404 trying to load http://playground.caleydo.org/caleydo_vis_proteinviewer/
- [ ] sample_app lists as its homepage caleydo.org
- [ ] sample_local_app might be unnecessary with the tutorial examples?
- [ ] sample_local_app also lists as its homepage caleydo.org
- [ ] taco lists as its homepage caleydo.org
- [ ] For vials, the project homepage is actually a better demo than the playground

Proposal: get rid of the project homepage links. They aren't being used well, or consistenly. better to make sure that if someone lands on the demo app or the github, they can find the homepage, if necessary.

**Comment by mstreit** [comment]
does not exist anymore
