### ISSUE TITLE
Wrong redirect for http / pathfinder

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo.github.io#191]
http://pathfinder.caleydoapp.org

seems to redirect to http://caleydo.org/publications/2016_eurovis_avocado/

https://pathfinder.caleydoapp.org/ (httpS) works as expected

**Comment by mstreit** [comment]
for me it points to the correct page.

**Comment by mstreit** [comment]
@alexsb, can you test again?

**Comment by thinkh** [comment]
Works for me as well.
