### ISSUE TITLE
Missing subdomain for help.caleydo.org

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo.github.io#193]
http://help.caleydo.org 
should point to 
http://caleydo.org/caleydo-doc/3.1/index.html#!index.md

**Comment by mstreit** [comment]
Since we migrated caleydo.org to AWS I don't have access anymore. @thinkh, how about you?

**Comment by thinkh** [comment]
AWS is only hosting the *.caleydoapp.org. The subdomain help.caleydo.org must be configured in the domain administration system, right?

**Comment by mstreit** [comment]
We also use AWS to manage caleydo.org. But I cannot see it with my access rights.

**Comment by thinkh** [comment]
The subdomain is working again. I documented my steps [here](https://github.com/phovea/deployment_scripts/issues/5).
