### ISSUE TITLE
setup / install information outdated

### ISSUE THREAD

**Issue by jaronimoe** [Caleydo/caleydo.github.io#208]
dear maintainers of Caleydo,

I wanted to first post this in the actual Caleydo repository but that seems to be read-only now.
anyway, the issue is also suitable for the webpage's repository:

the setup information on the webpage is outdated:
https://caleydo.org/releases/caleydo_3_1_5/

it says 
> Install the latest Java. Caleydo requires Oracle Java 7 (>= Java 7 Version 40).

however, Java 7 is officially not available for download anymore (not without an oracle account anyway). I then took the instruction literally and installed the *latest* java JDK, however in this case, Caleydo crashes on startup as it seems to be incompatible with the latest Java version.

are there more recent Java versions that are compatible with Caleydo, or
are there any plans to update Caleydo to support more recent Java versions?

in any case, it would be beneficial if you could update the setup information on the webpage accordingly.

thank you & kind regards,
Johannes

**Comment by alexsb** [comment]
Hi Johannes,

the Java version is not actively maintained. The page you're referring to isn't actually linked from the main page anymore, but we should add a discontinued warning, yes. 

We moved to a more heterogeneous and web-based approach in 2014. Tools that I can recommend for production right now are Taggle https://taggle.caleydoapp.org/ and UpSet http://vcg.github.io/upset/ - you're welcome to try to use the older tools, but I would expect there to be problems, like you described. 

Cheers,

Alex

**Comment by alexsb** [comment]
Added warning in 9d0fb0d65a441ddb3546b6e8f573c10e5f8c55eb

**Comment by jaronimoe** [comment]
dear Alex,

thank you for the clarification.
the page is actually still linked from the main page, via caleydo.org -> tools -> stratomex -> software / caleydo 3.1.5

cheers, Johannes

**Comment by mstreit** [comment]
Hi Johannes, yes, we want to keep it there for the take of reproducibility. 
Cheers, Marc
