### ISSUE TITLE
Tool images on homepage load very slowly

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo.github.io#68]
This is not pretty (despite being on Harvard network):

![mar 01 2016 15 52](https://cloud.githubusercontent.com/assets/1216518/13441530/a5573050-dfc5-11e5-8a47-266ee118898f.gif)

**Comment by alexsb** [comment]
hm, I notice what you mean. I've profiled it a bit: 

![image](https://cloud.githubusercontent.com/assets/2039375/13445697/f4dba3e0-dfca-11e5-9504-731883d3c362.png)

It looks like it's mainly the file size. But the size isn't huge, <300 kb. Maybe the CDN is slow today?

JKU logo is >100 kb, that's not necessary.

**Comment by thinkh** [comment]
@alexsb and @ngehlenborg is this still an issue? Otherwise please close the issue.

**Comment by mccalluc** [comment]
I don't think this is a top priority, but there is definitely room for improvement.

Chrome developer tools > Network > Throttle is helpful. Remember to clear your cache. This is from "Regular 3G":
<img width="1121" alt="screen shot 2016-09-16 at 12 00 46 pm" src="https://cloud.githubusercontent.com/assets/730388/18592760/71609ca4-7c06-11e6-8a1d-33eeb8eaa5d3.png">

- Note how late the image load starts: We're using JS to change the URL, but it can't run until jquery loads. (That also explains the 404 we get earlier: it's trying to fetch the incomplete URL.) An inline JS with a document.write (generally not a good idea) would let us insert randomized content into the DOM as the DOM is being created.
- I've checked, and the teaser PNGs can definitely be smaller. Typically 60%. I'll make a PR.
- I don't understand the long queuing times for the images... there might be something there?

**Comment by mccalluc** [comment]
Screen shot starts loading much earlier, and loads faster.
<img width="1117" alt="screen shot 2016-09-19 at 10 15 39 am" src="https://cloud.githubusercontent.com/assets/730388/18635175/164569d2-7e52-11e6-8efa-a783a81070f1.png">

**Comment by mccalluc** [comment]
Fixed by #144.
