### ISSUE TITLE
Create apps and plugin list for documentation dynamically using Jenkins

### ISSUE THREAD

**Issue by thinkh** [Caleydo/caleydo.github.io#71]
The [plugin list](http://www.caleydo.org/website/documentation/list_of_plugins/) and the [app list](http://www.caleydo.org/website/documentation/list_of_applications/) is maintained by hand at the moment.

I suggest to keep them up-to-date using Jenkins. Create Jenkins Job that does the following steps:

1. [Retrieve list of all Caleydo Github repos](https://api.github.com/users/Caleydo/repos)
2. Parse repos by name or identifier in package.json and categorize them as app or plugin
3. Write repo list to `/_data/applications.yml` or `/_data/plugins.yml`
5. Commit and push the changes to the yml
6. Jekyll should now re-generate the html pages

To show the yml list adapt the snippet from documentation navigation in `/_layouts/documentation.html`.

**Comment by ngehlenborg** [comment]
Could we use Travis?

**Comment by thinkh** [comment]
@ngehlenborg: I haven't worked with Travis so far. Could you explain what do you mean?

**Comment by ngehlenborg** [comment]
https://travis-ci.org

- advantages:
 - convenient integration with Github
 - free for public Github repos 
 - nice and clean UI
 - nice Slack integration
 - it's a hosted service, i.e. we don't have to worry about maintenance
 - anyone can easily be given access (unlike the Jenkins thing in Graz)

- disadvantages:
 - for closed source projects it would cost $129/month

**Comment by thinkh** [comment]
@ngehlenborg Please open a new issue, if you want to have a general discussion about Jenkins vs. Travis. ;-) I think a major point is the time we need to migrate all jenkins jobs to travis.

**Comment by thinkh** [comment]
I prepared the (static) yml files in 7a0ea86903d7ce426d27e4c79f3f78cf633bc325

**Comment by ngehlenborg** [comment]
We could start with the website, we don't have to move everything at once.

**Comment by thinkh** [comment]
Ok, I'll try and see how it works. :smile:

**Comment by thinkh** [comment]
@sgratzl Can I modify the existing [.travis.yml](https://github.com/Caleydo/website/blob/master/.travis.yml) and delete the [Rakefile](https://github.com/Caleydo/website/blob/master/Rakefile)? Or is it still in use somewhere?

**Comment by mccalluc** [comment]
Took a different approach with this, but I think it's good enough. We're constrained by the plugins github pages supports, but with #91 we have Travis check that that the repo list is up-to-date. So there isn't any auto-updating of the site as the remote README's change, but good enough for now.

**Comment by mstreit** [comment]
Looks great, thanks @mccalluc!
