### ISSUE TITLE
Make relative links work

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#79]
http://www.caleydo.org/documentation/architecture/ links to http://www.caleydo.org/documentation/architecture/plugin_mechanism

That's not what is intended: 
```
In Caleydo Web, all components are [plugins](plugin_mechanism).
```

Because of the trailing slash, the relative URL isn't working as expected. [architecture](http://www.caleydo.org/documentation/architecture) is redirected to [architecture/](http://www.caleydo.org/documentation/architecture/), and what should have been a relative url at the same level becomes a link down. Can we turn that off? 

(If we can't, we need to make these paths absolute.)

**Comment by alexsb** [comment]
A ../plugin_mechanism/ could be a workaround?
