### ISSUE TITLE
Should the Downloads page link to the new version?

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#87]
The home page links to https://github.com/Caleydo/, but it's probably hard for a new person to know where to go from there. The Downloads page does not link to any of the current code.

Also, is there a version number for the current code? I think we're calling it Caledo Web, but if the last Java version was 3.1.5, would it help in any context to identify the current code as Caledo 4?

**Comment by ngehlenborg** [comment]
Good points, @mccalluc. 

Re:GitHub destination - could we refer to the main Caleydo Web repo?

Re:versioning - @thinkh, can we put that on the agenda for one of our calls?

**Comment by alexsb** [comment]
All of this needs to be fixed eventually, but the Caleydo website right now only (intentionally) mentions caleydo web in passing, since we haven't officially released.

**Comment by mccalluc** [comment]
Thanks: That gives me a better sense of where we are. Since there's nothing immediately actionable here, I'll close it, and when there is an official release we won't overlook updating that page.

**Comment by thinkh** [comment]
@ngehlenborg I added this point to tomorrows agenda
