### ISSUE TITLE
Server Tutorial: ts:dev stalls

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#90]
Trying to walk through http://www.caleydo.org/documentation/tutorial/server/, and after I `./manage.sh server`, it seems to stall on `Running "ts:dev" (ts) task`.

**Comment by mstreit** [comment]
I've' tried it and got stuck at the resolve step:
```
vagrant@caleydo-web:/vagrant$ ./manage.sh resolve
--- resolving dependencies ---
./manage.sh: line 114: node_modules/.bin/caleydo: No such file or directory
```

**Comment by mstreit** [comment]
@thinkh Please try it on your machine as well.

**Comment by thinkh** [comment]
On my computer (Windows 10) it works without problems. I could follow every step without errors.

@mccalluc Are you using Mac or Windows?

**Comment by mstreit** [comment]
I've tried it again and it worked without problems (on Mac). My previous problem (see above) was probably related to the fact that I had another caleydo_web_container VM running at the time I tried to create a new one.

**Comment by mstreit** [comment]
@mccalluc Did you get it to work in the end?

**Comment by mccalluc** [comment]
No, I didn't, but I haven't spent time on this recently, either.

**Comment by mccalluc** [comment]
ok: I've added this to my Gruntfile, and am just calling grunt directly:
```
    ts: {
      fake: {
        src: ['fake.ts'],
        tsconfig: true
      },
```

Behavior is the same: `Running "ts:fake" (ts) task` and then it hangs. So it's not even reading the first file: the problem comes before that.

**Comment by mccalluc** [comment]
However, if I strip it down to 
```
module.exports = function(grunt) {
  grunt.initConfig({
    ts: {
      default : {
        src: ["plugins/*/*.ts", "!node_modules/**"]
      }
    }
  });
  grunt.loadNpmTasks("grunt-ts");
  grunt.registerTask("default", ["ts"]);
};
```
... it does seem to work... except I can't find the output files. I have used --out and --outfile, and while the run completes, I haven't found the output yet.

**Comment by mstreit** [comment]
@mccalluc Getting a fresh VM resolved your issue. Do you have an idea what the problem was?

**Comment by mccalluc** [comment]
Sadly, no. I deleted the image (mistake) so it can't be investigated further now. Closing. Sorry for wasting time on this.

**Comment by thinkh** [comment]
@bikramkawan n got the same error/behavior with MacOS. We investigated the error and found out that *caleydo_web_container/node_modules* was an actual directory with all the installed node modules inside. That is wrong! Instead it should be a symbolic link from the virtual machine inside the virtual machine, see here:
![ts-dev-stalls](https://cloud.githubusercontent.com/assets/5851088/19350472/30d21962-9158-11e6-8557-0a5716c2e197.png)

After we saw that we had some troubles to delete the acutal node_modules directory from within the VM. We had to create a new directory and delete that one. Might be some issue with MacOS time machine!?

To create the correct node_modules symbolic link, you can run the following lines from *caleydo_web_container/scripts/_vagrant_node.sh*:

```bash
mkdir -p /home/vagrant/caleydo_web/node_modules
chown vagrant:vagrant -R /home/vagrant/caleydo_web
ln -s /home/vagrant/caleydo_web/node_modules/ ./node_modules
```

After that it should look like as in the screenshot above. Don't forget to run `./manage.sh resolve` afterwards, to install the node_modules inside the VM.

@mccalluc: If you experience the same problem again, please try this steps and report here. Thanks.
