### ISSUE TITLE
Use official release version of bundle in quickstart_example.html

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#93]
- [x] 1) Right now, if I just replace `http://www.caleydo.org/documentation/caleydo/bundle.js` with `https://github.com/Caleydo/bundle_lib/releases/download/v0.0.1/caleydo.js` it doesn't work. Either tweak the example to work with the bundle, or release a new bundle.
- [ ] 2) Are the outside dependencies still needed, or are they in the bundle?
- [x] 3) Should CSS also be part of the release, so we could get rid of `http://caleydo.github.io/documentation/caleydo/bundle.css`?
- [x] 4) At the end, I think we should be able to get rid of the `_documentation/caleydo` directory.

**Comment by thinkh** [comment]
re 2) Maybe something like the call to http://www.caleydo.org/api/idtype that fails in the [tutorial](http://www.caleydo.org/documentation/tutorial/web_bundle/frame.html?2) (see console.log)?
