### ISSUE TITLE
Get quickstart_example.html working in jsfiddle

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#94]
https://jsfiddle.net/cpk47c4t/1/
- [ ] In the sidebar, I have https://caleydo.github.io/documentation/caleydo/bundle.css, but this redirects to http://www.caleydo.org/documentation/caleydo/bundle.css. If I try https instead on that url, I get a certificate error. In any event, this might be moot if we can version our CSS and distribute it with the JS.
- [ ] `ReferenceError: Caleydo is not defined`, though I've listed the bundle.js in the sidebar.

**Comment by mstreit** [comment]
You could try to add the css to the release (https://github.com/Caleydo/bundle_lib/releases).

**Comment by mstreit** [comment]
I've updated the js link to point to the github release of the lib, which works:
https://jsfiddle.net/6vo2x3yz/

**Comment by thinkh** [comment]
I created a ticket for the SSL certificate #101, since that has to be fixed anyway.

**Comment by mstreit** [comment]
I've added the CSS to the lib release, see https://github.com/Caleydo/bundle_lib/releases/tag/v0.0.1

**Comment by mstreit** [comment]
Linking to the css file hosted on Github results in the following problem:
`Resource interpreted as Stylesheet but transferred with MIME type application/octet-stream: "https://github-cloud.s3.amazonaws.com/releases/50174973/942d5750-73a9-11e6-…%20filename%3Dcaleydo.css&response-content-type=application%2Foctet-stream".`

**Comment by mccalluc** [comment]
@mstreit: Here's the best I can think of for the mime-type problem right now:

- I was hoping (again) that this mime-type problem was something rawgit.com could handle, but I am wrong again: Turns out it won't proxy files in a release, only the repo proper: https://github.com/rgrove/rawgit/issues/70 (There are a couple forks of rawgit out there and they have the same limitation: https://gitcdn.link/ ; https://raw.githack.com/)
- CDNJS will only consider libraries which are significantly more popular than ours, and are stable releases.
- Checking these object files into git would not be *the right thing to do*, but it would work, in conjunction with one of the services above.
- Or we host the libraries on s3? That's the best I can think of right now.
- Looked at cloudfront from aws, but that still requires the origin server to get the mime-types correct: There's no way in it to override the mime that comes from the server.

**Comment by thinkh** [comment]
The idea with the S3 storage was great. We created an S3 bucket and uploaded the library files there.

**Latest release**
* https://s3.amazonaws.com/caleydo-releases/latest/caleydo.css
* https://s3.amazonaws.com/caleydo-releases/latest/caleydo.js
* https://s3.amazonaws.com/caleydo-releases/latest/caleydo.min.css
* https://s3.amazonaws.com/caleydo-releases/latest/caleydo.min.js

**Versioned Release**

* https://s3.amazonaws.com/caleydo-releases/v0.0.1/caleydo.css
* https://s3.amazonaws.com/caleydo-releases/v0.0.1/caleydo.js
* https://s3.amazonaws.com/caleydo-releases/v0.0.1/caleydo.min.css
* https://s3.amazonaws.com/caleydo-releases/v0.0.1/caleydo.min.js

However, we need to update the Jenkins to upload the files automatically to S3.

I updated your JSFiddle using the new URLs: https://jsfiddle.net/cpk47c4t/3/

**Comment by mstreit** [comment]
Note that we cannot use the http://release.caleydo.org/latest/caleydo.* in the JSFiddle because only https includes are allowed. I suggest that we use the https://s3.amazonaws.com/caleydo-releases/latest/ links.
