### ISSUE TITLE
Row labelling off-by-one?

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#99]
In web_bundle/code-0.js I specify a matrix with the rows labelled from 1 to 8. When the code runs in the first iframe on http://www.caleydo.org/documentation/tutorial/web_bundle/, the row labels are shifted down by one, so I have a blank, and then 1 through 7. Am I using it wrong, or is there a bug?

**Comment by thinkh** [comment]
Can you try the following code:

```javascript
var matrix = Caleydo.d3.parser.parseMatrix([
  ['row_ids','A','B','C','D','E','F','G','H'],
  ['row1',0,0,1,1,1,1,0,0],
  ['row2',0,1,1,1,1,1,1,0],
  ['row3',1,1,0,1,1,0,1,1],
  ['row4',1,1,1,1,1,1,1,1],
  ['row5',1,1,1,1,1,1,1,1],
  ['row6',1,1,0,1,1,0,1,1],
  ['row7',0,1,1,0,0,1,1,0],
  ['row8',0,0,1,1,1,1,0,0]]);
```

**Comment by mstreit** [comment]
see https://github.com/Caleydo/caleydo_d3/blob/master/parser.ts

**Comment by mccalluc** [comment]
@thinkh: It's still offset:
```
ID		A	B	C	D	E	F	G	H
row_ids	0	0	1	1	1	1	0	0
row1	0	1	1	1	1	1	1	0
row2	1	1	0	1	1	0	1	1
row3	1	1	1	1	1	1	1	1
row4	1	1	1	1	1	1	1	1
row5	1	1	0	1	1	0	1	1
row6	0	1	1	0	0	1	1	0
row7	0	0	1	1	1	1	0	0
```

Glanced at the source file just now, and am not going to get anything done this evening, but I could try tomorrow and see how far I get...

**Comment by thinkh** [comment]
I had a look into the code and discovered that you should define the row and column ids separately.

```javascript
    var matrix = Caleydo.d3.parser.parseMatrix(
      [ // raw data as 2D array
        [0, 0, 1, 1, 1, 1, 0, 0],
        [0, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 0, 1, 1, 0, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 0, 1, 1, 0, 1, 1],
        [0, 1, 1, 0, 0, 1, 1, 0],
        [0, 0, 1, 1, 1, 1, 0, 0]
      ],
      [1, 2, 3, 4, 5, 6, 7, 8], // row_ids
      ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'] // col_ids
    );
```

[Try the updated JSFiddle ](https://jsfiddle.net/cpk47c4t/4/)
